name: Deploy to Github Pages

on: 
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Deploying to Github Pages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Set GitHub user
        run: echo "GIT_USER=aniljangra27" >> $GITHUB_ENV

      - name: Authorizing Github action
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
        uses: oleksiyrudenko/gha-git-credentials@v1

      - name: Install Dependency
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: amitsingh-007/deploy-to-github-pages@v1.1
        with:
          branch: gh-page
          folder: build
